//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxInAsp.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class AjaxEmployee
    {
        public int EmployeeID { get; set; }

        [Required(ErrorMessage ="This Filed is Required")]
        public string Name { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
        public Nullable<decimal> Salary { get; set; }

        [DisplayName ("Image")]
        public string ImagePath { get; set; }
        
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public AjaxEmployee()
        {
            ImagePath = "~/AppFiles/Images/default.png";
        }
    }
}
